language: cpp
os: linux
jobs:
  include:
    - dist: bionic
      addons:
        apt:
          packages:
            - libwxgtk3.0-dev
            - g++-8
            - cmake
      install: export CXX="g++-8" CC="gcc-8"
      before_script: cmake .
      script: make


